//! Input-method definition tables — ported from `input_method_def.go`.
//!
//! Go uses `map[string]string`; we use ordered `Vec<(&str, &str)>` so parsing is deterministic
//! (Go map iteration is randomized, but the engine is order-independent for the matched key).

pub type InputMethodDefinition = Vec<(&'static str, &'static str)>;

/// Returns the list of `(name, definition)` pairs, preserving a stable order.
pub fn input_method_definitions() -> Vec<(&'static str, InputMethodDefinition)> {
    vec![
        (
            "Telex",
            vec![
                ("z", "XoaDauThanh"),
                ("s", "DauSac"),
                ("f", "DauHuyen"),
                ("r", "DauHoi"),
                ("x", "DauNga"),
                ("j", "DauNang"),
                ("a", "A_Â"),
                ("e", "E_Ê"),
                ("o", "O_Ô"),
                ("w", "UOA_ƯƠĂ"),
                ("d", "D_Đ"),
            ],
        ),
        (
            "VNI",
            vec![
                ("0", "XoaDauThanh"),
                ("1", "DauSac"),
                ("2", "DauHuyen"),
                ("3", "DauHoi"),
                ("4", "DauNga"),
                ("5", "DauNang"),
                ("6", "AEO_ÂÊÔ"),
                ("7", "UO_ƯƠ"),
                ("8", "A_Ă"),
                ("9", "D_Đ"),
            ],
        ),
        (
            "VIQR",
            vec![
                ("0", "XoaDauThanh"),
                ("'", "DauSac"),
                ("`", "DauHuyen"),
                ("?", "DauHoi"),
                ("~", "DauNga"),
                (".", "DauNang"),
                ("^", "AEO_ÂÊÔ"),
                ("+", "UO_ƯƠ"),
                ("*", "UO_ƯƠ"),
                ("(", "A_Ă"),
                ("d", "D_Đ"),
            ],
        ),
        (
            "Microsoft layout",
            vec![
                ("8", "DauSac"),
                ("5", "DauHuyen"),
                ("6", "DauHoi"),
                ("7", "DauNga"),
                ("9", "DauNang"),
                ("1", "__ă"),
                ("!", "_Ă"),
                ("2", "__â"),
                ("@", "_Â"),
                ("3", "__ê"),
                ("#", "_Ê"),
                ("4", "__ô"),
                ("$", "_Ô"),
                ("0", "__đ"),
                (")", "_Đ"),
                ("[", "__ư"),
                ("{", "_Ư"),
                ("]", "__ơ"),
                ("}", "_Ơ"),
            ],
        ),
        (
            "Telex 2",
            vec![
                ("z", "XoaDauThanh"),
                ("s", "DauSac"),
                ("f", "DauHuyen"),
                ("r", "DauHoi"),
                ("x", "DauNga"),
                ("j", "DauNang"),
                ("a", "A_Â"),
                ("e", "E_Ê"),
                ("o", "O_Ô"),
                ("w", "UOA_ƯƠĂ__Ư"),
                ("d", "D_Đ"),
                ("]", "__ư"),
                ("[", "__ơ"),
                ("}", "_Ư"),
                ("{", "_Ơ"),
            ],
        ),
        (
            "Telex + VNI",
            vec![
                ("z", "XoaDauThanh"),
                ("s", "DauSac"),
                ("f", "DauHuyen"),
                ("r", "DauHoi"),
                ("x", "DauNga"),
                ("j", "DauNang"),
                ("a", "A_Â"),
                ("e", "E_Ê"),
                ("o", "O_Ô"),
                ("w", "UOA_ƯƠĂ"),
                ("d", "D_Đ"),
                ("0", "XoaDauThanh"),
                ("1", "DauSac"),
                ("2", "DauHuyen"),
                ("3", "DauHoi"),
                ("4", "DauNga"),
                ("5", "DauNang"),
                ("6", "AEO_ÂÊÔ"),
                ("7", "UO_ƯƠ"),
                ("8", "A_Ă"),
                ("9", "D_Đ"),
            ],
        ),
        (
            "Telex + VNI + VIQR",
            vec![
                ("z", "XoaDauThanh"),
                ("s", "DauSac"),
                ("f", "DauHuyen"),
                ("r", "DauHoi"),
                ("x", "DauNga"),
                ("j", "DauNang"),
                ("a", "A_Â"),
                ("e", "E_Ê"),
                ("o", "O_Ô"),
                ("w", "UOA_ƯƠĂ"),
                ("d", "D_Đ"),
                ("0", "XoaDauThanh"),
                ("1", "DauSac"),
                ("2", "DauHuyen"),
                ("3", "DauHoi"),
                ("4", "DauNga"),
                ("5", "DauNang"),
                ("6", "AEO_ÂÊÔ"),
                ("7", "UO_ƯƠ"),
                ("8", "A_Ă"),
                ("9", "D_Đ"),
                ("'", "DauSac"),
                ("`", "DauHuyen"),
                ("?", "DauHoi"),
                ("~", "DauNga"),
                (".", "DauNang"),
                ("^", "AEO_ÂÊÔ"),
                ("+", "UO_ƯƠ"),
                ("*", "UO_ƯƠ"),
                ("(", "A_Ă"),
                ("\\", "D_Đ"),
            ],
        ),
        (
            "VNI Bàn phím tiếng Pháp",
            vec![
                ("&", "XoaDauThanh"),
                ("é", "DauSac"),
                ("\"", "DauHuyen"),
                ("'", "DauHoi"),
                ("(", "DauNga"),
                ("-", "DauNang"),
                ("è", "AEO_ÂÊÔ"),
                ("_", "UO_ƯƠ"),
                ("ç", "A_Ă"),
                ("à", "D_Đ"),
            ],
        ),
        (
            "Telex W",
            vec![
                ("z", "XoaDauThanh"),
                ("s", "DauSac"),
                ("f", "DauHuyen"),
                ("r", "DauHoi"),
                ("x", "DauNga"),
                ("j", "DauNang"),
                ("a", "A_Â"),
                ("e", "E_Ê"),
                ("o", "O_Ô"),
                ("w", "UOA_ƯƠĂ__Ư"),
                ("d", "D_Đ"),
            ],
        ),
    ]
}
